# Generated by Django 4.1.1 on 2022-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts_images/default_post.jpg', upload_to='posts_images/'),
        ),
    ]
