# Generated by Django 4.1.1 on 2022-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_is_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_artist',
        ),
        migrations.AddField(
            model_name='profile',
            name='artistId',
            field=models.IntegerField(default=0),
        ),
    ]
