# Generated by Django 4.1.1 on 2022-09-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_email_artist_phone_alter_artist_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
